export const TAX_RATE_ERROR_CODES = {
  NOT_FOUND: "TAX_RATE_NOT_FOUND",
  VALIDATION_ERROR: "TAX_RATE_VALIDATION_ERROR",
  ACTIVE_RATE_ALREADY_EXISTS: "TAX_RATE_ACTIVE_ALREADY_EXISTS",
  IMMUTABLE: "TAX_RATE_IMMUTABLE",
  TRANSACTION_FAILED: "TAX_RATE_TRANSACTION_FAILED",
} as const;

export type TaxRateErrorCode =
  (typeof TAX_RATE_ERROR_CODES)[keyof typeof TAX_RATE_ERROR_CODES];
