export const NOTIFICATION_PREFERENCE_ERROR_CODES = {
  VALIDATION_ERROR: "NOTIFICATION_PREFERENCE_VALIDATION_ERROR",
  NOT_FOUND: "NOTIFICATION_PREFERENCE_NOT_FOUND",
  REPOSITORY_ERROR: "NOTIFICATION_PREFERENCE_REPOSITORY_ERROR",
} as const;

export type NotificationPreferenceErrorCode =
  (typeof NOTIFICATION_PREFERENCE_ERROR_CODES)[keyof typeof NOTIFICATION_PREFERENCE_ERROR_CODES];
