export const ORGANIZATION_ERROR_CODES = {
  VALIDATION_ERROR: "ORGANIZATION_VALIDATION_ERROR",
  NOT_FOUND: "ORGANIZATION_NOT_FOUND",
  SLUG_ALREADY_EXISTS: "ORGANIZATION_SLUG_ALREADY_EXISTS",
  REPOSITORY_ERROR: "ORGANIZATION_REPOSITORY_ERROR",
} as const;

export type OrganizationErrorCode =
  (typeof ORGANIZATION_ERROR_CODES)[keyof typeof ORGANIZATION_ERROR_CODES];
