export const INVOICE_ERROR_CODES = {
  VALIDATION_ERROR: "INVOICE_VALIDATION_ERROR",
  NOT_FOUND: "INVOICE_NOT_FOUND",
  ORDER_NOT_FOUND: "INVOICE_ORDER_NOT_FOUND",
  ALREADY_EXISTS: "INVOICE_ALREADY_EXISTS",
  INVALID_TRANSITION: "INVOICE_INVALID_TRANSITION",
  IMMUTABLE: "INVOICE_IMMUTABLE",
  TRANSACTION_FAILED: "INVOICE_TRANSACTION_FAILED",
} as const;

export type InvoiceErrorCode =
  (typeof INVOICE_ERROR_CODES)[keyof typeof INVOICE_ERROR_CODES];
