export const FEATURE_FLAG_ERROR_CODES = {
  NOT_FOUND: "FEATURE_FLAG_NOT_FOUND",
  VALIDATION_ERROR: "FEATURE_FLAG_VALIDATION_ERROR",
  STORE_NOT_FOUND: "FEATURE_FLAG_STORE_NOT_FOUND",
  DUPLICATE_KEY: "FEATURE_FLAG_DUPLICATE_KEY",
  REPOSITORY_ERROR: "FEATURE_FLAG_REPOSITORY_ERROR",
  FORBIDDEN_SCOPE: "FEATURE_FLAG_FORBIDDEN_SCOPE",
} as const;

export type FeatureFlagErrorCode =
  (typeof FEATURE_FLAG_ERROR_CODES)[keyof typeof FEATURE_FLAG_ERROR_CODES];
