export const REPLENISHMENT_ERROR_CODES = {
  NOT_FOUND: "REPLENISHMENT_NOT_FOUND",
  RULE_NOT_FOUND: "REPLENISHMENT_RULE_NOT_FOUND",
  RECOMMENDATION_NOT_FOUND: "REPLENISHMENT_RECOMMENDATION_NOT_FOUND",
  RULE_ALREADY_EXISTS: "REPLENISHMENT_RULE_ALREADY_EXISTS",
  DUPLICATE_PENDING_RECOMMENDATION: "REPLENISHMENT_DUPLICATE_PENDING_RECOMMENDATION",
  INVALID_RECOMMENDATION_STATUS: "REPLENISHMENT_INVALID_RECOMMENDATION_STATUS",
  VALIDATION_ERROR: "REPLENISHMENT_VALIDATION_ERROR",
  TRANSACTION_FAILED: "REPLENISHMENT_TRANSACTION_FAILED",
} as const;

export type ReplenishmentErrorCode =
  (typeof REPLENISHMENT_ERROR_CODES)[keyof typeof REPLENISHMENT_ERROR_CODES];
