export const OPERATIONS_ERROR_CODES = {
  VALIDATION_ERROR: "OPERATIONS_VALIDATION_ERROR",
  STORE_NOT_FOUND: "OPERATIONS_STORE_NOT_FOUND",
} as const;

export type OperationsErrorCode =
  (typeof OPERATIONS_ERROR_CODES)[keyof typeof OPERATIONS_ERROR_CODES];
