export const INVENTORY_ALLOCATION_ERROR_CODES = {
  VALIDATION_ERROR: "INVENTORY_ALLOCATION_VALIDATION_ERROR",
  ALLOCATION_NOT_FOUND: "INVENTORY_ALLOCATION_NOT_FOUND",
  PICK_LIST_ITEM_NOT_FOUND: "INVENTORY_ALLOCATION_PICK_LIST_ITEM_NOT_FOUND",
  INVENTORY_NOT_FOUND: "INVENTORY_ALLOCATION_INVENTORY_NOT_FOUND",
  INSUFFICIENT_INVENTORY: "INVENTORY_ALLOCATION_INSUFFICIENT_INVENTORY",
  QUANTITY_EXCEEDED: "INVENTORY_ALLOCATION_QUANTITY_EXCEEDED",
  ALLOCATION_IMMUTABLE: "INVENTORY_ALLOCATION_IMMUTABLE",
  SHIPMENT_NOT_ELIGIBLE: "INVENTORY_ALLOCATION_SHIPMENT_NOT_ELIGIBLE",
  PICK_LIST_NOT_MUTABLE: "INVENTORY_ALLOCATION_PICK_LIST_NOT_MUTABLE",
  VARIANT_MISMATCH: "INVENTORY_ALLOCATION_VARIANT_MISMATCH",
  ORDER_ITEM_NOT_FOUND: "INVENTORY_ALLOCATION_ORDER_ITEM_NOT_FOUND",
  TRANSACTION_FAILED: "INVENTORY_ALLOCATION_TRANSACTION_FAILED",
} as const;

export type InventoryAllocationErrorCode =
  (typeof INVENTORY_ALLOCATION_ERROR_CODES)[keyof typeof INVENTORY_ALLOCATION_ERROR_CODES];
