export const PLATFORM_HARDENING_ERROR_CODES = {
  VALIDATION_ERROR: "PLATFORM_HARDENING_VALIDATION_ERROR",
  NOT_FOUND: "PLATFORM_HARDENING_NOT_FOUND",
  RATE_LIMITED: "PLATFORM_HARDENING_RATE_LIMITED",
  REPOSITORY_ERROR: "PLATFORM_HARDENING_REPOSITORY_ERROR",
} as const;

export type PlatformHardeningErrorCode =
  (typeof PLATFORM_HARDENING_ERROR_CODES)[keyof typeof PLATFORM_HARDENING_ERROR_CODES];
