export const INVENTORY_ADJUSTMENT_ERROR_CODES = {
  VALIDATION_ERROR: "INVENTORY_ADJUSTMENT_VALIDATION_ERROR",
  ADJUSTMENT_NOT_FOUND: "INVENTORY_ADJUSTMENT_NOT_FOUND",
  INVENTORY_ITEM_NOT_FOUND: "INVENTORY_ADJUSTMENT_INVENTORY_ITEM_NOT_FOUND",
  INSUFFICIENT_STOCK: "INVENTORY_ADJUSTMENT_INSUFFICIENT_STOCK",
  TRANSACTION_FAILED: "INVENTORY_ADJUSTMENT_TRANSACTION_FAILED",
} as const;

export type InventoryAdjustmentErrorCode =
  (typeof INVENTORY_ADJUSTMENT_ERROR_CODES)[keyof typeof INVENTORY_ADJUSTMENT_ERROR_CODES];
