export const SHIPMENT_ERROR_CODES = {
  VALIDATION_ERROR: "SHIPMENT_VALIDATION_ERROR",
  NOT_FOUND: "SHIPMENT_NOT_FOUND",
  ORDER_NOT_FOUND: "SHIPMENT_ORDER_NOT_FOUND",
  ORDER_NOT_FULFILLED: "SHIPMENT_ORDER_NOT_FULFILLED",
  SHIPPING_ADDRESS_INCOMPLETE: "SHIPMENT_SHIPPING_ADDRESS_INCOMPLETE",
  ALREADY_EXISTS: "SHIPMENT_ALREADY_EXISTS",
  INVALID_TRANSITION: "SHIPMENT_INVALID_TRANSITION",
  TRANSACTION_FAILED: "SHIPMENT_TRANSACTION_FAILED",
  CARRIER_ERROR: "SHIPMENT_CARRIER_ERROR",
  UNSUPPORTED_CARRIER: "SHIPMENT_UNSUPPORTED_CARRIER",
} as const;

export type ShipmentErrorCode =
  (typeof SHIPMENT_ERROR_CODES)[keyof typeof SHIPMENT_ERROR_CODES];
