/** Store-scoped permission codes enforced at the API boundary. */
export const STORE_PERMISSIONS = [
  "catalogue:read",
  "catalogue:write",
  "inventory:read",
  "inventory:write",
  "orders:read",
  "orders:write",
  "orders:lifecycle",
  "orders:fulfill",
  "reservations:manage",
  "audit:read",
  "customers:read",
  "customers:write",
  "carts:read",
  "carts:write",
  "payments:read",
  "payments:write",
  "payments:lifecycle",
  "invoices:read",
  "invoices:write",
  "invoices:lifecycle",
  "refunds:read",
  "refunds:write",
  "refunds:lifecycle",
  "promotions:read",
  "promotions:write",
  "tax-rates:read",
  "tax-rates:write",
  "shipments:read",
  "shipments:write",
  "shipments:lifecycle",
  "shipping-config:read",
  "shipping-config:write",
  "warehouses:read",
  "warehouses:write",
  "warehouse-transfers:read",
  "warehouse-transfers:write",
  "warehouse-transfers:lifecycle",
  "purchase-orders:read",
  "purchase-orders:write",
  "purchase-orders:lifecycle",
  "suppliers:read",
  "suppliers:write",
  "replenishment:read",
  "replenishment:write",
  "operations:read",
  "operations:run",
  "reports:read",
  "notifications:read",
  "notifications:write",
  "jobs:read",
  "jobs:write",
  "stores:read",
  "stores:write",
] as const;

export type StorePermissionCode = (typeof STORE_PERMISSIONS)[number];
