/** Store-scoped permission codes enforced at the API boundary. */
export const STORE_PERMISSIONS = [
  "catalogue:read",
  "catalogue:write",
  "inventory:read",
  "inventory:write",
  "orders:read",
  "orders:write",
  "orders:lifecycle",
  "orders:fulfill",
  "reservations:manage",
  "audit:read",
  "customers:read",
  "customers:write",
  "carts:read",
  "carts:write",
  "payments:read",
  "payments:write",
  "payments:lifecycle",
  "invoices:read",
  "invoices:write",
  "invoices:lifecycle",
  "refunds:read",
  "refunds:write",
  "refunds:lifecycle",
  "promotions:read",
  "promotions:write",
  "tax-rates:read",
  "tax-rates:write",
  "shipments:read",
  "shipments:write",
  "shipments:lifecycle",
  "shipping-config:read",
  "shipping-config:write",
] as const;

export type StorePermissionCode = (typeof STORE_PERMISSIONS)[number];
