export const EMAIL_ERROR_CODES = {
  UNSUPPORTED_PROVIDER: "EMAIL_UNSUPPORTED_PROVIDER",
  VALIDATION_ERROR: "EMAIL_VALIDATION_ERROR",
  RECIPIENT_REQUIRED: "EMAIL_RECIPIENT_REQUIRED",
} as const;

export type EmailErrorCode =
  (typeof EMAIL_ERROR_CODES)[keyof typeof EMAIL_ERROR_CODES];
