export const AUTH_ERROR_CODES = {
  VALIDATION_ERROR: "AUTH_VALIDATION_ERROR",
  EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
  SESSION_REVOKED: "AUTH_SESSION_REVOKED",
  UNAUTHENTICATED: "AUTH_UNAUTHENTICATED",
  USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
} as const;

export type AuthErrorCode =
  (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
