export const SHIPMENT_PACKAGE_ERROR_CODES = {
  VALIDATION_ERROR: "SHIPMENT_PACKAGE_VALIDATION_ERROR",
  SHIPMENT_NOT_FOUND: "SHIPMENT_PACKAGE_SHIPMENT_NOT_FOUND",
  PACKAGE_NOT_FOUND: "SHIPMENT_PACKAGE_NOT_FOUND",
  SHIPMENT_NOT_MUTABLE: "SHIPMENT_PACKAGE_SHIPMENT_NOT_MUTABLE",
  TRANSACTION_FAILED: "SHIPMENT_PACKAGE_TRANSACTION_FAILED",
} as const;

export type ShipmentPackageErrorCode =
  (typeof SHIPMENT_PACKAGE_ERROR_CODES)[keyof typeof SHIPMENT_PACKAGE_ERROR_CODES];
