export const DISASTER_READINESS_ERROR_CODES = {
  VALIDATION_ERROR: "DISASTER_READINESS_VALIDATION_ERROR",
  REPOSITORY_ERROR: "DISASTER_READINESS_REPOSITORY_ERROR",
} as const;

export type DisasterReadinessErrorCode =
  (typeof DISASTER_READINESS_ERROR_CODES)[keyof typeof DISASTER_READINESS_ERROR_CODES];
