import type { StorePermissionCode, StoreRole } from "@commerceflow/types";

const ALL_STORE_PERMISSIONS: readonly StorePermissionCode[] = [
  "catalogue:read",
  "catalogue:write",
  "inventory:read",
  "inventory:write",
  "orders:read",
  "orders:write",
  "orders:lifecycle",
  "orders:fulfill",
  "reservations:manage",
  "audit:read",
  "customers:read",
  "customers:write",
  "carts:read",
  "carts:write",
  "payments:read",
  "payments:write",
  "payments:lifecycle",
  "invoices:read",
  "invoices:write",
  "invoices:lifecycle",
  "refunds:read",
  "refunds:write",
  "refunds:lifecycle",
  "promotions:read",
  "promotions:write",
  "tax-rates:read",
  "tax-rates:write",
  "shipments:read",
  "shipments:write",
  "shipments:lifecycle",
  "shipping-config:read",
  "shipping-config:write",
  "warehouses:read",
  "warehouses:write",
  "warehouse-transfers:read",
  "warehouse-transfers:write",
  "warehouse-transfers:lifecycle",
  "purchase-orders:read",
  "purchase-orders:write",
  "purchase-orders:lifecycle",
  "suppliers:read",
  "suppliers:write",
  "replenishment:read",
  "replenishment:write",
    "operations:read",
    "operations:run",
    "reports:read",
    "notifications:read",
    "notifications:write",
    "jobs:read",
    "jobs:write",
    "stores:read",
    "stores:write",
    "imports:read",
    "imports:write",
    "exports:read",
    "exports:write",
    "api-keys:read",
    "api-keys:write",
    "webhooks:read",
    "webhooks:write",
    "feature-flags:read",
    "feature-flags:write",
    "platform:read",
    "platform:write",
];

const PERMISSIONS_BY_STORE_ROLE: Readonly<
  Record<StoreRole, readonly StorePermissionCode[]>
> = {
  owner: ALL_STORE_PERMISSIONS,
  admin: ALL_STORE_PERMISSIONS.filter(
    (permission) => permission !== "platform:write",
  ),
  manager: [
    "catalogue:read",
    "catalogue:write",
    "inventory:read",
    "inventory:write",
    "orders:read",
    "orders:write",
    "orders:lifecycle",
    "orders:fulfill",
    "reservations:manage",
    "audit:read",
    "customers:read",
    "customers:write",
    "carts:read",
    "carts:write",
    "payments:read",
    "payments:write",
    "payments:lifecycle",
    "invoices:read",
    "invoices:write",
    "invoices:lifecycle",
    "refunds:read",
    "refunds:write",
    "refunds:lifecycle",
    "promotions:read",
    "promotions:write",
    "tax-rates:read",
    "tax-rates:write",
    "shipments:read",
    "shipments:write",
    "shipments:lifecycle",
    "shipping-config:read",
    "shipping-config:write",
    "warehouses:read",
    "warehouses:write",
    "warehouse-transfers:read",
    "warehouse-transfers:write",
    "warehouse-transfers:lifecycle",
    "purchase-orders:read",
    "purchase-orders:write",
    "purchase-orders:lifecycle",
    "suppliers:read",
    "suppliers:write",
    "replenishment:read",
    "replenishment:write",
    "operations:read",
    "operations:run",
    "reports:read",
    "notifications:read",
    "notifications:write",
    "jobs:read",
    "jobs:write",
    "stores:read",
    "stores:write",
    "imports:read",
    "imports:write",
    "exports:read",
    "exports:write",
    "api-keys:read",
    "webhooks:read",
    "webhooks:write",
    "feature-flags:read",
  ],
  staff: [
    "catalogue:read",
    "inventory:read",
    "orders:read",
    "orders:write",
    "customers:read",
    "carts:read",
    "carts:write",
    "payments:read",
    "invoices:read",
    "refunds:read",
    "promotions:read",
    "tax-rates:read",
    "shipments:read",
    "shipping-config:read",
    "warehouses:read",
    "warehouse-transfers:read",
    "purchase-orders:read",
    "suppliers:read",
    "replenishment:read",
    "operations:read",
    "reports:read",
    "notifications:read",
    "jobs:read",
    "stores:read",
    "imports:read",
    "exports:read",
    "api-keys:read",
    "webhooks:read",
    "feature-flags:read",
  ],
};

export const StorePermissionPolicy = {
  permissionsForRole(role: StoreRole): readonly StorePermissionCode[] {
    return PERMISSIONS_BY_STORE_ROLE[role];
  },

  hasPermission(role: StoreRole, permission: StorePermissionCode): boolean {
    return PERMISSIONS_BY_STORE_ROLE[role].includes(permission);
  },
} as const;
