export const PROMOTION_ERROR_CODES = {
  VALIDATION_ERROR: "PROMOTION_VALIDATION_ERROR",
  NOT_FOUND: "PROMOTION_NOT_FOUND",
  CODE_ALREADY_EXISTS: "PROMOTION_CODE_ALREADY_EXISTS",
  TRANSACTION_FAILED: "PROMOTION_TRANSACTION_FAILED",
} as const;

export type PromotionErrorCode =
  (typeof PROMOTION_ERROR_CODES)[keyof typeof PROMOTION_ERROR_CODES];
