export const WAREHOUSE_TRANSFER_ERROR_CODES = {
  VALIDATION_ERROR: "WAREHOUSE_TRANSFER_VALIDATION_ERROR",
  WAREHOUSE_TRANSFER_NOT_FOUND: "WAREHOUSE_TRANSFER_NOT_FOUND",
  WAREHOUSE_NOT_FOUND: "WAREHOUSE_TRANSFER_WAREHOUSE_NOT_FOUND",
  INVENTORY_ITEM_NOT_FOUND: "WAREHOUSE_TRANSFER_INVENTORY_ITEM_NOT_FOUND",
  INVALID_STATUS_TRANSITION: "WAREHOUSE_TRANSFER_INVALID_STATUS_TRANSITION",
  WAREHOUSE_TRANSFER_IMMUTABLE: "WAREHOUSE_TRANSFER_IMMUTABLE",
  INSUFFICIENT_STOCK: "WAREHOUSE_TRANSFER_INSUFFICIENT_STOCK",
  SAME_WAREHOUSE: "WAREHOUSE_TRANSFER_SAME_WAREHOUSE",
  TRANSACTION_FAILED: "WAREHOUSE_TRANSFER_TRANSACTION_FAILED",
} as const;

export type WarehouseTransferErrorCode =
  (typeof WAREHOUSE_TRANSFER_ERROR_CODES)[keyof typeof WAREHOUSE_TRANSFER_ERROR_CODES];
