export const FULFILLMENT_ERROR_CODES = {
  VALIDATION_ERROR: "FULFILLMENT_VALIDATION_ERROR",
  ORDER_NOT_FOUND: "FULFILLMENT_ORDER_NOT_FOUND",
  ORDER_NOT_CONFIRMED: "FULFILLMENT_ORDER_NOT_CONFIRMED",
  ORDER_ALREADY_FULFILLED: "FULFILLMENT_ORDER_ALREADY_FULFILLED",
  NO_ACTIVE_RESERVATIONS: "FULFILLMENT_NO_ACTIVE_RESERVATIONS",
  INSUFFICIENT_RESERVED_STOCK: "FULFILLMENT_INSUFFICIENT_RESERVED_STOCK",
  RESERVATION_MISMATCH: "FULFILLMENT_RESERVATION_MISMATCH",
} as const;

export type FulfillmentErrorCode =
  (typeof FULFILLMENT_ERROR_CODES)[keyof typeof FULFILLMENT_ERROR_CODES];
