/** Entity types referenced by immutable audit log entries. */
export const AUDIT_ENTITY_TYPES = [
  "brand",
  "category",
  "product",
  "inventory_item",
  "stock_movement",
  "order",
  "inventory_reservation",
  "customer",
  "customer_address",
  "cart",
  "cart_item",
  "checkout",
  "payment",
  "invoice",
  "refund",
  "promotion",
  "promotion_redemption",
  "tax_rate",
  "shipment",
  "shipment_tracking_event",
  "shipment_package",
  "pick_list",
  "inventory_allocation",
  "return",
  "inventory_adjustment",
  "cycle_count",
  "shipping_zone",
  "shipping_method",
  "warehouse",
  "warehouse_transfer",
  "purchase_order",
  "supplier",
  "supplier_contact",
  "replenishment_rule",
  "replenishment_recommendation",
  "operations",
  "report",
  "sales_report",
  "inventory_report",
  "customer_report",
  "financial_report",
  "procurement_report",
] as const;

export type AuditEntityType = (typeof AUDIT_ENTITY_TYPES)[number];
