export const RESERVATION_ERROR_CODES = {
  VALIDATION_ERROR: "RESERVATION_VALIDATION_ERROR",
  NOT_FOUND: "RESERVATION_NOT_FOUND",
  ORDER_NOT_FOUND: "RESERVATION_ORDER_NOT_FOUND",
  ORDER_NOT_CONFIRMED: "RESERVATION_ORDER_NOT_CONFIRMED",
  INVENTORY_NOT_FOUND: "RESERVATION_INVENTORY_NOT_FOUND",
  INSUFFICIENT_STOCK: "RESERVATION_INSUFFICIENT_STOCK",
  ALREADY_RESERVED: "RESERVATION_ALREADY_RESERVED",
  ALREADY_RELEASED: "RESERVATION_ALREADY_RELEASED",
} as const;

export type ReservationErrorCode =
  (typeof RESERVATION_ERROR_CODES)[keyof typeof RESERVATION_ERROR_CODES];
