export const API_KEY_ERROR_CODES = {
  VALIDATION_ERROR: "API_KEY_VALIDATION_ERROR",
  NOT_FOUND: "API_KEY_NOT_FOUND",
  INVALID_KEY: "API_KEY_INVALID",
  REVOKED: "API_KEY_REVOKED",
  EXPIRED: "API_KEY_EXPIRED",
  INSUFFICIENT_PERMISSION: "API_KEY_INSUFFICIENT_PERMISSION",
  ALREADY_REVOKED: "API_KEY_ALREADY_REVOKED",
  REPOSITORY_ERROR: "API_KEY_REPOSITORY_ERROR",
} as const;

export type ApiKeyErrorCode =
  (typeof API_KEY_ERROR_CODES)[keyof typeof API_KEY_ERROR_CODES];
