export const DATA_TRANSFER_ERROR_CODES = {
  VALIDATION_ERROR: "DATA_TRANSFER_VALIDATION_ERROR",
  NOT_FOUND: "DATA_TRANSFER_NOT_FOUND",
  REPOSITORY_ERROR: "DATA_TRANSFER_REPOSITORY_ERROR",
} as const;

export type DataTransferErrorCode =
  (typeof DATA_TRANSFER_ERROR_CODES)[keyof typeof DATA_TRANSFER_ERROR_CODES];
