/** Internal domain event type identifiers. */
export const DOMAIN_EVENT_TYPES = [
  "order.confirmed",
  "order.cancelled",
  "order.fulfilled",
  "inventory.reserved",
  "inventory.released",
  "customer.created",
  "customer.updated",
  "customer.address.created",
  "customer.address.updated",
  "cart.created",
  "cart.item.added",
  "cart.item.updated",
  "cart.item.removed",
  "checkout.completed",
  "payment.created",
  "payment.authorized",
  "payment.paid",
  "payment.failed",
  "payment.cancelled",
  "invoice.created",
  "invoice.issued",
  "invoice.paid",
  "invoice.voided",
  "refund.created",
  "refund.completed",
  "refund.cancelled",
  "promotion.created",
  "promotion.updated",
  "promotion.deleted",
  "promotion.applied",
  "promotion.removed",
  "tax.created",
  "tax.updated",
  "tax.activated",
  "tax.deactivated",
  "shipment.created",
  "shipment.shipped",
  "shipment.delivered",
  "shipment.cancelled",
  "shipment.tracking.updated",
  "shipping-zone.created",
  "shipping-zone.updated",
  "shipping-zone.deleted",
  "shipping-method.created",
  "shipping-method.updated",
  "shipping-method.deleted",
] as const;

export type DomainEventType = (typeof DOMAIN_EVENT_TYPES)[number];
