export const PAYMENT_ERROR_CODES = {
  VALIDATION_ERROR: "PAYMENT_VALIDATION_ERROR",
  NOT_FOUND: "PAYMENT_NOT_FOUND",
  ORDER_NOT_FOUND: "PAYMENT_ORDER_NOT_FOUND",
  AMOUNT_MISMATCH: "PAYMENT_AMOUNT_MISMATCH",
  CURRENCY_MISMATCH: "PAYMENT_CURRENCY_MISMATCH",
  INVALID_TRANSITION: "PAYMENT_INVALID_TRANSITION",
  TRANSACTION_FAILED: "PAYMENT_TRANSACTION_FAILED",
  GATEWAY_ERROR: "PAYMENT_GATEWAY_ERROR",
  UNSUPPORTED_PROVIDER: "PAYMENT_UNSUPPORTED_PROVIDER",
} as const;

export type PaymentErrorCode =
  (typeof PAYMENT_ERROR_CODES)[keyof typeof PAYMENT_ERROR_CODES];
