export const NOTIFICATION_ERROR_CODES = {
  NOT_FOUND: "NOTIFICATION_NOT_FOUND",
  VALIDATION_ERROR: "NOTIFICATION_VALIDATION_ERROR",
  UNSUPPORTED_PROVIDER: "NOTIFICATION_UNSUPPORTED_PROVIDER",
  PROVIDER_ERROR: "NOTIFICATION_PROVIDER_ERROR",
  REPOSITORY_ERROR: "NOTIFICATION_REPOSITORY_ERROR",
} as const;

export type NotificationErrorCode =
  (typeof NOTIFICATION_ERROR_CODES)[keyof typeof NOTIFICATION_ERROR_CODES];
