export const INVENTORY_ERROR_CODES = {
  VALIDATION_ERROR: "INVENTORY_VALIDATION_ERROR",
  NOT_FOUND: "INVENTORY_NOT_FOUND",
  VARIANT_NOT_FOUND: "INVENTORY_VARIANT_NOT_FOUND",
  ALREADY_EXISTS: "INVENTORY_ALREADY_EXISTS",
  INSUFFICIENT_STOCK: "INVENTORY_INSUFFICIENT_STOCK",
} as const;

export type InventoryErrorCode =
  (typeof INVENTORY_ERROR_CODES)[keyof typeof INVENTORY_ERROR_CODES];
