export const CART_ERROR_CODES = {
  NOT_FOUND: "CART_NOT_FOUND",
  ITEM_NOT_FOUND: "CART_ITEM_NOT_FOUND",
  VALIDATION_ERROR: "CART_VALIDATION_ERROR",
  VARIANT_NOT_FOUND: "CART_VARIANT_NOT_FOUND",
  CURRENCY_MISMATCH: "CART_CURRENCY_MISMATCH",
  ALREADY_ACTIVE: "CART_ALREADY_ACTIVE",
  IMMUTABLE: "CART_IMMUTABLE",
  CUSTOMER_NOT_FOUND: "CART_CUSTOMER_NOT_FOUND",
} as const;

export type CartErrorCode =
  (typeof CART_ERROR_CODES)[keyof typeof CART_ERROR_CODES];
