export const WEBHOOK_ERROR_CODES = {
  VALIDATION_ERROR: "WEBHOOK_VALIDATION_ERROR",
  NOT_FOUND: "WEBHOOK_NOT_FOUND",
  REPOSITORY_ERROR: "WEBHOOK_REPOSITORY_ERROR",
  DELIVERY_ERROR: "WEBHOOK_DELIVERY_ERROR",
} as const;

export type WebhookErrorCode =
  (typeof WEBHOOK_ERROR_CODES)[keyof typeof WEBHOOK_ERROR_CODES];
