export const WAREHOUSE_ERROR_CODES = {
  NOT_FOUND: "WAREHOUSE_NOT_FOUND",
  VALIDATION_ERROR: "WAREHOUSE_VALIDATION_ERROR",
  CODE_ALREADY_EXISTS: "WAREHOUSE_CODE_ALREADY_EXISTS",
  CANNOT_DELETE_DEFAULT: "WAREHOUSE_CANNOT_DELETE_DEFAULT",
  CANNOT_DEACTIVATE_DEFAULT: "WAREHOUSE_CANNOT_DEACTIVATE_DEFAULT",
  DEFAULT_WAREHOUSE_REQUIRED: "WAREHOUSE_DEFAULT_REQUIRED",
  TRANSACTION_FAILED: "WAREHOUSE_TRANSACTION_FAILED",
} as const;

export type WarehouseErrorCode =
  (typeof WAREHOUSE_ERROR_CODES)[keyof typeof WAREHOUSE_ERROR_CODES];
