export const JOB_ERROR_CODES = {
  NOT_FOUND: "JOB_NOT_FOUND",
  VALIDATION_ERROR: "JOB_VALIDATION_ERROR",
  ALREADY_COMPLETED: "JOB_ALREADY_COMPLETED",
  INVALID_STATE: "JOB_INVALID_STATE",
  EXECUTOR_ERROR: "JOB_EXECUTOR_ERROR",
  REPOSITORY_ERROR: "JOB_REPOSITORY_ERROR",
} as const;

export type JobErrorCode =
  (typeof JOB_ERROR_CODES)[keyof typeof JOB_ERROR_CODES];
