export const REPORTS_ERROR_CODES = {
  VALIDATION_ERROR: "REPORTS_VALIDATION_ERROR",
  STORE_NOT_FOUND: "REPORTS_STORE_NOT_FOUND",
  INVALID_DATE_RANGE: "REPORTS_INVALID_DATE_RANGE",
} as const;

export type ReportsErrorCode =
  (typeof REPORTS_ERROR_CODES)[keyof typeof REPORTS_ERROR_CODES];
