export const PROMOTION_REDEMPTION_ERROR_CODES = {
  VALIDATION_ERROR: "PROMOTION_REDEMPTION_VALIDATION_ERROR",
  CART_NOT_FOUND: "PROMOTION_REDEMPTION_CART_NOT_FOUND",
  CART_NOT_ACTIVE: "PROMOTION_REDEMPTION_CART_NOT_ACTIVE",
  PROMOTION_NOT_FOUND: "PROMOTION_REDEMPTION_PROMOTION_NOT_FOUND",
  PROMOTION_NOT_ACTIVE: "PROMOTION_REDEMPTION_PROMOTION_NOT_ACTIVE",
  PROMOTION_NOT_ELIGIBLE: "PROMOTION_REDEMPTION_PROMOTION_NOT_ELIGIBLE",
  PROMOTION_NOT_APPLIED: "PROMOTION_REDEMPTION_PROMOTION_NOT_APPLIED",
  CURRENCY_MISMATCH: "PROMOTION_REDEMPTION_CURRENCY_MISMATCH",
  TRANSACTION_FAILED: "PROMOTION_REDEMPTION_TRANSACTION_FAILED",
} as const;

export type PromotionRedemptionErrorCode =
  (typeof PROMOTION_REDEMPTION_ERROR_CODES)[keyof typeof PROMOTION_REDEMPTION_ERROR_CODES];
