export const CATALOGUE_ERROR_CODES = {
  VALIDATION_ERROR: "CATALOGUE_VALIDATION_ERROR",
  NOT_FOUND: "CATALOGUE_NOT_FOUND",
  SLUG_ALREADY_EXISTS: "CATALOGUE_SLUG_ALREADY_EXISTS",
  SKU_ALREADY_EXISTS: "CATALOGUE_SKU_ALREADY_EXISTS",
  CATEGORY_NOT_FOUND: "CATALOGUE_CATEGORY_NOT_FOUND",
  BRAND_NOT_FOUND: "CATALOGUE_BRAND_NOT_FOUND",
  PARENT_CYCLE: "CATALOGUE_PARENT_CYCLE",
  PRODUCT_MEDIA_NOT_FOUND: "CATALOGUE_PRODUCT_MEDIA_NOT_FOUND",
  PRODUCT_MEDIA_REORDER_MISMATCH: "CATALOGUE_PRODUCT_MEDIA_REORDER_MISMATCH",
  PRODUCT_VARIANT_NOT_FOUND: "CATALOGUE_PRODUCT_VARIANT_NOT_FOUND",
  LAST_VARIANT_REQUIRED: "CATALOGUE_LAST_VARIANT_REQUIRED",
} as const;

export type CatalogueErrorCode =
  (typeof CATALOGUE_ERROR_CODES)[keyof typeof CATALOGUE_ERROR_CODES];
