export const AUTHORIZATION_ERROR_CODES = {
  STORE_ACCESS_DENIED: "AUTHORIZATION_STORE_ACCESS_DENIED",
  INSUFFICIENT_PERMISSION: "AUTHORIZATION_INSUFFICIENT_PERMISSION",
} as const;

export type AuthorizationErrorCode =
  (typeof AUTHORIZATION_ERROR_CODES)[keyof typeof AUTHORIZATION_ERROR_CODES];
