export const SMS_ERROR_CODES = {
  UNSUPPORTED_PROVIDER: "SMS_UNSUPPORTED_PROVIDER",
  VALIDATION_ERROR: "SMS_VALIDATION_ERROR",
  RECIPIENT_REQUIRED: "SMS_RECIPIENT_REQUIRED",
} as const;

export type SmsErrorCode =
  (typeof SMS_ERROR_CODES)[keyof typeof SMS_ERROR_CODES];
