export const PURCHASE_ORDER_ERROR_CODES = {
  VALIDATION_ERROR: "PURCHASE_ORDER_VALIDATION_ERROR",
  PURCHASE_ORDER_NOT_FOUND: "PURCHASE_ORDER_NOT_FOUND",
  WAREHOUSE_NOT_FOUND: "PURCHASE_ORDER_WAREHOUSE_NOT_FOUND",
  SUPPLIER_NOT_FOUND: "PURCHASE_ORDER_SUPPLIER_NOT_FOUND",
  PRODUCT_VARIANT_NOT_FOUND: "PURCHASE_ORDER_PRODUCT_VARIANT_NOT_FOUND",
  PURCHASE_ORDER_ITEM_NOT_FOUND: "PURCHASE_ORDER_ITEM_NOT_FOUND",
  INVALID_STATUS_TRANSITION: "PURCHASE_ORDER_INVALID_STATUS_TRANSITION",
  PURCHASE_ORDER_IMMUTABLE: "PURCHASE_ORDER_IMMUTABLE",
  RECEIPT_EXCEEDS_REMAINING: "PURCHASE_ORDER_RECEIPT_EXCEEDS_REMAINING",
  ITEM_ALREADY_RECEIVED: "PURCHASE_ORDER_ITEM_ALREADY_RECEIVED",
  TRANSACTION_FAILED: "PURCHASE_ORDER_TRANSACTION_FAILED",
} as const;

export type PurchaseOrderErrorCode =
  (typeof PURCHASE_ORDER_ERROR_CODES)[keyof typeof PURCHASE_ORDER_ERROR_CODES];
