export const SUPPLIER_ERROR_CODES = {
  NOT_FOUND: "SUPPLIER_NOT_FOUND",
  CONTACT_NOT_FOUND: "SUPPLIER_CONTACT_NOT_FOUND",
  CODE_ALREADY_EXISTS: "SUPPLIER_CODE_ALREADY_EXISTS",
  VALIDATION_ERROR: "SUPPLIER_VALIDATION_ERROR",
  TRANSACTION_FAILED: "SUPPLIER_TRANSACTION_FAILED",
} as const;

export type SupplierErrorCode =
  (typeof SUPPLIER_ERROR_CODES)[keyof typeof SUPPLIER_ERROR_CODES];
