export const PICK_LIST_ERROR_CODES = {
  VALIDATION_ERROR: "PICK_LIST_VALIDATION_ERROR",
  SHIPMENT_NOT_FOUND: "PICK_LIST_SHIPMENT_NOT_FOUND",
  PICK_LIST_NOT_FOUND: "PICK_LIST_NOT_FOUND",
  SHIPMENT_NOT_ELIGIBLE: "PICK_LIST_SHIPMENT_NOT_ELIGIBLE",
  ACTIVE_PICK_LIST_EXISTS: "PICK_LIST_ACTIVE_EXISTS",
  INVALID_TRANSITION: "PICK_LIST_INVALID_TRANSITION",
  QUANTITY_EXCEEDED: "PICK_LIST_QUANTITY_EXCEEDED",
  INCOMPLETE_PICK: "PICK_LIST_INCOMPLETE_PICK",
  PICKING_NOT_COMPLETE: "PICK_LIST_PICKING_NOT_COMPLETE",
  ORDER_ITEM_NOT_FOUND: "PICK_LIST_ORDER_ITEM_NOT_FOUND",
  TRANSACTION_FAILED: "PICK_LIST_TRANSACTION_FAILED",
} as const;

export type PickListErrorCode =
  (typeof PICK_LIST_ERROR_CODES)[keyof typeof PICK_LIST_ERROR_CODES];
