export const DEPLOYMENT_READINESS_ERROR_CODES = {
  VALIDATION_ERROR: "DEPLOYMENT_READINESS_VALIDATION_ERROR",
  REPOSITORY_ERROR: "DEPLOYMENT_READINESS_REPOSITORY_ERROR",
} as const;

export type DeploymentReadinessErrorCode =
  (typeof DEPLOYMENT_READINESS_ERROR_CODES)[keyof typeof DEPLOYMENT_READINESS_ERROR_CODES];
