export const CHECKOUT_ERROR_CODES = {
  VALIDATION_ERROR: "CHECKOUT_VALIDATION_ERROR",
  CART_NOT_FOUND: "CHECKOUT_CART_NOT_FOUND",
  CART_NOT_ACTIVE: "CHECKOUT_CART_NOT_ACTIVE",
  EMPTY_CART: "CHECKOUT_EMPTY_CART",
  CUSTOMER_NOT_FOUND: "CHECKOUT_CUSTOMER_NOT_FOUND",
  ADDRESS_NOT_FOUND: "CHECKOUT_ADDRESS_NOT_FOUND",
  ADDRESS_NOT_OWNED: "CHECKOUT_ADDRESS_NOT_OWNED",
  VARIANT_NOT_FOUND: "CHECKOUT_VARIANT_NOT_FOUND",
  CURRENCY_MISMATCH: "CHECKOUT_CURRENCY_MISMATCH",
  SHIPPING_METHOD_NOT_FOUND: "CHECKOUT_SHIPPING_METHOD_NOT_FOUND",
  SHIPPING_METHOD_INACTIVE: "CHECKOUT_SHIPPING_METHOD_INACTIVE",
  SHIPPING_ZONE_NOT_FOUND: "CHECKOUT_SHIPPING_ZONE_NOT_FOUND",
  SHIPPING_ZONE_INACTIVE: "CHECKOUT_SHIPPING_ZONE_INACTIVE",
  SHIPPING_COUNTRY_NOT_COVERED: "CHECKOUT_SHIPPING_COUNTRY_NOT_COVERED",
  SHIPPING_CURRENCY_MISMATCH: "CHECKOUT_SHIPPING_CURRENCY_MISMATCH",
  TRANSACTION_FAILED: "CHECKOUT_TRANSACTION_FAILED",
} as const;

export type CheckoutErrorCode =
  (typeof CHECKOUT_ERROR_CODES)[keyof typeof CHECKOUT_ERROR_CODES];
