export const CHECKOUT_ERROR_CODES = {
  VALIDATION_ERROR: "CHECKOUT_VALIDATION_ERROR",
  CART_NOT_FOUND: "CHECKOUT_CART_NOT_FOUND",
  CART_NOT_ACTIVE: "CHECKOUT_CART_NOT_ACTIVE",
  EMPTY_CART: "CHECKOUT_EMPTY_CART",
  CUSTOMER_NOT_FOUND: "CHECKOUT_CUSTOMER_NOT_FOUND",
  ADDRESS_NOT_FOUND: "CHECKOUT_ADDRESS_NOT_FOUND",
  ADDRESS_NOT_OWNED: "CHECKOUT_ADDRESS_NOT_OWNED",
  VARIANT_NOT_FOUND: "CHECKOUT_VARIANT_NOT_FOUND",
  CURRENCY_MISMATCH: "CHECKOUT_CURRENCY_MISMATCH",
  TRANSACTION_FAILED: "CHECKOUT_TRANSACTION_FAILED",
} as const;

export type CheckoutErrorCode =
  (typeof CHECKOUT_ERROR_CODES)[keyof typeof CHECKOUT_ERROR_CODES];
