export const SHIPPING_METHOD_ERROR_CODES = {
  VALIDATION_ERROR: "SHIPPING_METHOD_VALIDATION_ERROR",
  NOT_FOUND: "SHIPPING_METHOD_NOT_FOUND",
  ZONE_NOT_FOUND: "SHIPPING_METHOD_ZONE_NOT_FOUND",
  INACTIVE_ZONE_REQUIRED: "SHIPPING_METHOD_INACTIVE_ZONE_REQUIRED",
  TRANSACTION_FAILED: "SHIPPING_METHOD_TRANSACTION_FAILED",
} as const;

export type ShippingMethodErrorCode =
  (typeof SHIPPING_METHOD_ERROR_CODES)[keyof typeof SHIPPING_METHOD_ERROR_CODES];
