export const SHIPPING_ZONE_ERROR_CODES = {
  VALIDATION_ERROR: "SHIPPING_ZONE_VALIDATION_ERROR",
  NOT_FOUND: "SHIPPING_ZONE_NOT_FOUND",
  HAS_ACTIVE_METHODS: "SHIPPING_ZONE_HAS_ACTIVE_METHODS",
  TRANSACTION_FAILED: "SHIPPING_ZONE_TRANSACTION_FAILED",
} as const;

export type ShippingZoneErrorCode =
  (typeof SHIPPING_ZONE_ERROR_CODES)[keyof typeof SHIPPING_ZONE_ERROR_CODES];
