export const CYCLE_COUNT_ERROR_CODES = {
  VALIDATION_ERROR: "CYCLE_COUNT_VALIDATION_ERROR",
  CYCLE_COUNT_NOT_FOUND: "CYCLE_COUNT_NOT_FOUND",
  WAREHOUSE_NOT_FOUND: "CYCLE_COUNT_WAREHOUSE_NOT_FOUND",
  INVENTORY_ITEM_NOT_FOUND: "CYCLE_COUNT_INVENTORY_ITEM_NOT_FOUND",
  INVALID_STATUS_TRANSITION: "CYCLE_COUNT_INVALID_STATUS_TRANSITION",
  CYCLE_COUNT_IMMUTABLE: "CYCLE_COUNT_IMMUTABLE",
  CYCLE_COUNT_ITEM_NOT_FOUND: "CYCLE_COUNT_ITEM_NOT_FOUND",
  INSUFFICIENT_STOCK: "CYCLE_COUNT_INSUFFICIENT_STOCK",
  TRANSACTION_FAILED: "CYCLE_COUNT_TRANSACTION_FAILED",
} as const;

export type CycleCountErrorCode =
  (typeof CYCLE_COUNT_ERROR_CODES)[keyof typeof CYCLE_COUNT_ERROR_CODES];
