export const PLATFORM_OPERATIONS_ERROR_CODES = {
  VALIDATION_ERROR: "PLATFORM_OPERATIONS_VALIDATION_ERROR",
  REPOSITORY_ERROR: "PLATFORM_OPERATIONS_REPOSITORY_ERROR",
  NOT_READY: "PLATFORM_OPERATIONS_NOT_READY",
} as const;

export type PlatformOperationsErrorCode =
  (typeof PLATFORM_OPERATIONS_ERROR_CODES)[keyof typeof PLATFORM_OPERATIONS_ERROR_CODES];
