export const SHIPMENT_TRACKING_ERROR_CODES = {
  VALIDATION_ERROR: "SHIPMENT_TRACKING_VALIDATION_ERROR",
  SHIPMENT_NOT_FOUND: "SHIPMENT_TRACKING_SHIPMENT_NOT_FOUND",
  TRANSACTION_FAILED: "SHIPMENT_TRACKING_TRANSACTION_FAILED",
} as const;

export type ShipmentTrackingErrorCode =
  (typeof SHIPMENT_TRACKING_ERROR_CODES)[keyof typeof SHIPMENT_TRACKING_ERROR_CODES];
