export const RETURN_ERROR_CODES = {
  VALIDATION_ERROR: "RETURN_VALIDATION_ERROR",
  RETURN_NOT_FOUND: "RETURN_NOT_FOUND",
  ORDER_NOT_FOUND: "RETURN_ORDER_NOT_FOUND",
  SHIPMENT_NOT_FOUND: "RETURN_SHIPMENT_NOT_FOUND",
  SHIPMENT_NOT_FULFILLED: "RETURN_SHIPMENT_NOT_FULFILLED",
  INVALID_STATUS_TRANSITION: "RETURN_INVALID_STATUS_TRANSITION",
  RETURN_IMMUTABLE: "RETURN_IMMUTABLE",
  QUANTITY_EXCEEDED: "RETURN_QUANTITY_EXCEEDED",
  RETURN_ITEM_NOT_FOUND: "RETURN_ITEM_NOT_FOUND",
  INVENTORY_ITEM_MISMATCH: "RETURN_INVENTORY_ITEM_MISMATCH",
  TRANSACTION_FAILED: "RETURN_TRANSACTION_FAILED",
} as const;

export type ReturnErrorCode =
  (typeof RETURN_ERROR_CODES)[keyof typeof RETURN_ERROR_CODES];
