export const LOAD_TESTING_ERROR_CODES = {
  VALIDATION_ERROR: "LOAD_TESTING_VALIDATION_ERROR",
  REPOSITORY_ERROR: "LOAD_TESTING_REPOSITORY_ERROR",
} as const;

export type LoadTestingErrorCode =
  (typeof LOAD_TESTING_ERROR_CODES)[keyof typeof LOAD_TESTING_ERROR_CODES];
