export const ORDER_ERROR_CODES = {
  VALIDATION_ERROR: "ORDER_VALIDATION_ERROR",
  NOT_FOUND: "ORDER_NOT_FOUND",
  VARIANT_NOT_FOUND: "ORDER_VARIANT_NOT_FOUND",
  CURRENCY_MISMATCH: "ORDER_CURRENCY_MISMATCH",
  IMMUTABLE: "ORDER_IMMUTABLE",
} as const;

export type OrderErrorCode =
  (typeof ORDER_ERROR_CODES)[keyof typeof ORDER_ERROR_CODES];
