export const DATABASE_OPTIMIZATION_ERROR_CODES = {
  VALIDATION_ERROR: "DATABASE_OPTIMIZATION_VALIDATION_ERROR",
  REPOSITORY_ERROR: "DATABASE_OPTIMIZATION_REPOSITORY_ERROR",
} as const;

export type DatabaseOptimizationErrorCode =
  (typeof DATABASE_OPTIMIZATION_ERROR_CODES)[keyof typeof DATABASE_OPTIMIZATION_ERROR_CODES];
