export const STORE_ADMINISTRATION_ERROR_CODES = {
  VALIDATION_ERROR: "STORE_ADMINISTRATION_VALIDATION_ERROR",
  NOT_FOUND: "STORE_ADMINISTRATION_NOT_FOUND",
  SLUG_ALREADY_EXISTS: "STORE_ADMINISTRATION_SLUG_ALREADY_EXISTS",
  REPOSITORY_ERROR: "STORE_ADMINISTRATION_REPOSITORY_ERROR",
} as const;

export type StoreAdministrationErrorCode =
  (typeof STORE_ADMINISTRATION_ERROR_CODES)[keyof typeof STORE_ADMINISTRATION_ERROR_CODES];
