export const REFUND_ERROR_CODES = {
  VALIDATION_ERROR: "REFUND_VALIDATION_ERROR",
  NOT_FOUND: "REFUND_NOT_FOUND",
  PAYMENT_NOT_FOUND: "REFUND_PAYMENT_NOT_FOUND",
  PAYMENT_NOT_REFUNDABLE: "REFUND_PAYMENT_NOT_REFUNDABLE",
  ALREADY_EXISTS: "REFUND_ALREADY_EXISTS",
  INVALID_TRANSITION: "REFUND_INVALID_TRANSITION",
  IMMUTABLE: "REFUND_IMMUTABLE",
  TRANSACTION_FAILED: "REFUND_TRANSACTION_FAILED",
} as const;

export type RefundErrorCode =
  (typeof REFUND_ERROR_CODES)[keyof typeof REFUND_ERROR_CODES];
