export const CUSTOMER_ERROR_CODES = {
  NOT_FOUND: "CUSTOMER_NOT_FOUND",
  VALIDATION_ERROR: "CUSTOMER_VALIDATION_ERROR",
  EMAIL_ALREADY_EXISTS: "CUSTOMER_EMAIL_ALREADY_EXISTS",
} as const;

export type CustomerErrorCode =
  (typeof CUSTOMER_ERROR_CODES)[keyof typeof CUSTOMER_ERROR_CODES];
